# Feature Engineering on Adult Dataset

## What is Feature Engineering?

### Feature engineering is the process of transforming raw data into meaningful features that improve model performance.

## Why Feature Engineering is Important
1. Improves Model Accuracy : 
    Good features help models capture real patterns.

2. Helps Handle Data Issues
    Skewness → log transform
    Sparsity → binary flags
    High categories → grouping

3. Makes Patterns Learnable
    Models struggle with:
        Non-linear relationships & Complex interactions
        Feature engineering simplifies them.

4. Reduces Overfitting
    Too many categories → overfitting
    Grouping → better generalization

5. Sometimes More Important Than Model Choice
    A simple model + good features can outperform, A complex model + poor features

## Types of Feature Engineering
1. Transformation (Changing existing features)
  Examples:
    Log transformation
    Scaling
    Normalization
    Used for: Skewed data & Linear models

2. Feature Creation (Creating new features)
    Combines or derives new meaning

3. Binning (Discretization)
    Convert continuous values into categories
    Helps: Capture non-linearity & Improve interpretability

4. Encoding (Categorical → Numeric)
  Types:
    One-hot encoding
    Label encoding
    OneHotEncoder()
   Encoding is required because models only understand numbers.

5. Feature Extraction
    Extract useful info from existing data

6. Feature Interaction
    Combine features to capture relationships

7. Feature Reduction / Grouping
    Reduce complexity
    Helps avoid: High dimensionality & Overfitting

8. Feature Selection (Closely related)
    Choose most important features
    Remove irrelevant ones (fnlwgt)
    Keep high-impact features

In [27]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder, StandardScaler, LabelEncoder, FunctionTransformer
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

In [130]:
df = pd.read_csv(r"C:\Users\saran\OneDrive\Documents\Radhika\ML\ML-Project-Team7-\adult_cleaned_data.csv")

# Income Column

In [132]:
# Processing Target Variable:
df['income'] = df['income'].str.strip()
df['income'] = df['income'].map({'<=50K': 0, '>50K': 1})

### The target variable income was encoded into binary format (0 and 1) to make it suitable for machine learning models.

In [133]:
df.head()

,age,workclass,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income,capital_net
0,39,State-gov,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,0,2174
1,50,Self-emp-not-inc,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,0,0
2,38,Private,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,0,0
3,53,Private,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,0,0
4,28,Private,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,0,0

## Age Column

In [79]:
# Grouping Age columns into bin and lebelling them
#df['age_group'] = pd.cut(df['age'], bins=[17,25,45,65,100], labels=['Young','Adult','Mid-age','Senior'])
# Keeping Age as numerical column only

## Race and Sex

In [134]:
df['sex'].unique()

array(['Male', 'Female'], dtype=object)

In [135]:
# Binary transformation for sex column
df['sex'] = df['sex'].map({'Male': 1, 'Female': 0})
df

,age,workclass,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income,capital_net
0,39,State-gov,13,Never-married,Adm-clerical,Not-in-family,White,1,2174,0,40,United-States,0,2174
1,50,Self-emp-not-inc,13,Married-civ-spouse,Exec-managerial,Husband,White,1,0,0,13,United-States,0,0
2,38,Private,9,Divorced,Handlers-cleaners,Not-in-family,White,1,0,0,40,United-States,0,0
3,53,Private,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,1,0,0,40,United-States,0,0
4,28,Private,13,Married-civ-spouse,Prof-specialty,Wife,Black,0,0,0,40,Cuba,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,39,Private,13,Divorced,Prof-specialty,Not-in-family,White,0,0,0,36,United-States,0,0
48838,64,Unknown,9,Widowed,Unknown,Other-relative,Black,1,0,0,40,United-States,0,0
48839,38,Private,13,Married-civ-spouse,Prof-specialty,Husband,White,1,0,0,50,United-States,0,0
48840,44,Private,13,Divorced,Adm-clerical,Own-child,Asian-Pac-Islander,1,5455,0,40,United-States,0,5455
48841,35,Self-emp-inc,13,Married-civ-spouse,Exec-managerial,Husband,White,1,0,0,60,United-States,1,0

In [35]:
df['race'].value_counts()

race
White                 41762
Black                  4685
Asian-Pac-Islander     1519
Amer-Indian-Eskimo      470
Other                   406
Name: count, dtype: int64

In [136]:
### One-Hot Encoding Race Column
### No false ordering and Works for all models
race_dummies = pd.get_dummies(df['race'], prefix='race')

df = pd.concat([df,race_dummies], axis=1)
df = df.drop('race', axis=1)

### Dropping original 'race' column after onehot encoding

In [123]:
df

,age,education_num,sex,capital_gain,capital_loss,hours_per_week,native_country,income,capital_net,race_Amer-Indian-Eskimo,...,rel_Unmarried,rel_Wife,workclass_Government,workclass_Other,workclass_Private,workclass_Self-employed,occupation_Blue-collar,occupation_Other,occupation_Service,occupation_White-collar
0,39,13,NaN,2174,0,40,1,0,2174,False,...,False,False,True,False,False,False,False,False,True,False
1,50,13,NaN,0,0,13,1,0,0,False,...,False,False,False,False,False,True,False,False,False,True
2,38,9,NaN,0,0,40,1,0,0,False,...,False,False,False,False,True,False,False,True,False,False
3,53,7,NaN,0,0,40,1,0,0,False,...,False,False,False,False,True,False,False,True,False,False
4,28,13,NaN,0,0,40,0,0,0,False,...,False,True,False,False,True,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,39,13,NaN,0,0,36,1,0,0,False,...,False,False,False,False,True,False,False,False,False,True
48838,64,9,NaN,0,0,40,1,0,0,False,...,False,False,False,True,False,False,False,True,False,False
48839,38,13,NaN,0,0,50,1,0,0,False,...,False,False,False,False,True,False,False,False,False,True
48840,44,13,NaN,5455,0,40,1,0,5455,False,...,False,False,False,False,True,False,False,False,True,False
48841,35,13,NaN,0,0,60,1,1,0,False,...,False,False,False,False,False,True,False,False,False,True

# Hours_Per_Week Column

In [8]:
df['hours_per_week'].value_counts().head(10)

hours_per_week
40    22803
50     4246
45     2717
60     2177
35     1937
20     1862
30     1700
55     1051
25      958
48      770
Name: count, dtype: int64

In [137]:
df['hours_bin'] = pd.cut(df['hours_per_week'],
                        bins=[0,25,40,60,100],
                        labels=['Part-time','Full-time','Overtime','Heavy'])
df

,age,workclass,education_num,marital_status,occupation,relationship,sex,capital_gain,capital_loss,hours_per_week,native_country,income,capital_net,race_Amer-Indian-Eskimo,race_Asian-Pac-Islander,race_Black,race_Other,race_White,hours_bin
0,39,State-gov,13,Never-married,Adm-clerical,Not-in-family,1,2174,0,40,United-States,0,2174,False,False,False,False,True,Full-time
1,50,Self-emp-not-inc,13,Married-civ-spouse,Exec-managerial,Husband,1,0,0,13,United-States,0,0,False,False,False,False,True,Part-time
2,38,Private,9,Divorced,Handlers-cleaners,Not-in-family,1,0,0,40,United-States,0,0,False,False,False,False,True,Full-time
3,53,Private,7,Married-civ-spouse,Handlers-cleaners,Husband,1,0,0,40,United-States,0,0,False,False,True,False,False,Full-time
4,28,Private,13,Married-civ-spouse,Prof-specialty,Wife,0,0,0,40,Cuba,0,0,False,False,True,False,False,Full-time
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,39,Private,13,Divorced,Prof-specialty,Not-in-family,0,0,0,36,United-States,0,0,False,False,False,False,True,Full-time
48838,64,Unknown,9,Widowed,Unknown,Other-relative,1,0,0,40,United-States,0,0,False,False,True,False,False,Full-time
48839,38,Private,13,Married-civ-spouse,Prof-specialty,Husband,1,0,0,50,United-States,0,0,False,False,False,False,True,Overtime
48840,44,Private,13,Divorced,Adm-clerical,Own-child,1,5455,0,40,United-States,0,5455,False,True,False,False,False,Full-time
48841,35,Self-emp-inc,13,Married-civ-spouse,Exec-managerial,Husband,1,0,0,60,United-States,1,0,False,False,False,False,True,Overtime

In [138]:
## Onehot Encoding Hours_per_week_bin column
hours_bin_dummies = pd.get_dummies(df['hours_bin'], prefix='hours')
df = pd.concat([df,hours_bin_dummies], axis=1)
df = df.drop('hours_bin', axis=1)
df

,age,workclass,education_num,marital_status,occupation,relationship,sex,capital_gain,capital_loss,hours_per_week,...,capital_net,race_Amer-Indian-Eskimo,race_Asian-Pac-Islander,race_Black,race_Other,race_White,hours_Part-time,hours_Full-time,hours_Overtime,hours_Heavy
0,39,State-gov,13,Never-married,Adm-clerical,Not-in-family,1,2174,0,40,...,2174,False,False,False,False,True,False,True,False,False
1,50,Self-emp-not-inc,13,Married-civ-spouse,Exec-managerial,Husband,1,0,0,13,...,0,False,False,False,False,True,True,False,False,False
2,38,Private,9,Divorced,Handlers-cleaners,Not-in-family,1,0,0,40,...,0,False,False,False,False,True,False,True,False,False
3,53,Private,7,Married-civ-spouse,Handlers-cleaners,Husband,1,0,0,40,...,0,False,False,True,False,False,False,True,False,False
4,28,Private,13,Married-civ-spouse,Prof-specialty,Wife,0,0,0,40,...,0,False,False,True,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,39,Private,13,Divorced,Prof-specialty,Not-in-family,0,0,0,36,...,0,False,False,False,False,True,False,True,False,False
48838,64,Unknown,9,Widowed,Unknown,Other-relative,1,0,0,40,...,0,False,False,True,False,False,False,True,False,False
48839,38,Private,13,Married-civ-spouse,Prof-specialty,Husband,1,0,0,50,...,0,False,False,False,False,True,False,False,True,False
48840,44,Private,13,Divorced,Adm-clerical,Own-child,1,5455,0,40,...,5455,False,True,False,False,False,False,True,False,False
48841,35,Self-emp-inc,13,Married-civ-spouse,Exec-managerial,Husband,1,0,0,60,...,0,False,False,False,False,True,False,False,True,False

# Marital_Status Column

In [139]:
def group_marital(x):
    if x in ['Married-civ-spouse', 'Married-AF-spouse']:
        return 'Married'
    elif x in ['Divorced', 'Separated']:
        return 'Separated'
    else:
        return 'Single'

df['marital_group'] = df['marital_status'].apply(group_marital)

In [140]:
# OneHot Encoding marital_status_group column
marital_dummies = pd.get_dummies(df['marital_group'], prefix='marital')
df = pd.concat([df,marital_dummies], axis=1)
df = df.drop('marital_group', axis=1)
df = df.drop('marital_status', axis=1)
df

,age,workclass,education_num,occupation,relationship,sex,capital_gain,capital_loss,hours_per_week,native_country,...,race_Black,race_Other,race_White,hours_Part-time,hours_Full-time,hours_Overtime,hours_Heavy,marital_Married,marital_Separated,marital_Single
0,39,State-gov,13,Adm-clerical,Not-in-family,1,2174,0,40,United-States,...,False,False,True,False,True,False,False,False,False,True
1,50,Self-emp-not-inc,13,Exec-managerial,Husband,1,0,0,13,United-States,...,False,False,True,True,False,False,False,True,False,False
2,38,Private,9,Handlers-cleaners,Not-in-family,1,0,0,40,United-States,...,False,False,True,False,True,False,False,False,True,False
3,53,Private,7,Handlers-cleaners,Husband,1,0,0,40,United-States,...,True,False,False,False,True,False,False,True,False,False
4,28,Private,13,Prof-specialty,Wife,0,0,0,40,Cuba,...,True,False,False,False,True,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,39,Private,13,Prof-specialty,Not-in-family,0,0,0,36,United-States,...,False,False,True,False,True,False,False,False,True,False
48838,64,Unknown,9,Unknown,Other-relative,1,0,0,40,United-States,...,True,False,False,False,True,False,False,False,False,True
48839,38,Private,13,Prof-specialty,Husband,1,0,0,50,United-States,...,False,False,True,False,False,True,False,True,False,False
48840,44,Private,13,Adm-clerical,Own-child,1,5455,0,40,United-States,...,False,False,False,False,True,False,False,False,True,False
48841,35,Self-emp-inc,13,Exec-managerial,Husband,1,0,0,60,United-States,...,False,False,True,False,False,True,False,True,False,False

# Relationship Column: Onehot Encoding

In [34]:
df['relationship'].value_counts()

relationship
Husband           19716
Not-in-family     12583
Own-child          7581
Unmarried          5125
Wife               2331
Other-relative     1506
Name: count, dtype: int64

In [141]:
## Dropping original 'relationship column after Onehot Encoding
rel_dummies = pd.get_dummies(df['relationship'], prefix='rel')
df = pd.concat([df,rel_dummies], axis=1)
df = df.drop('relationship', axis=1)
df

,age,workclass,education_num,occupation,sex,capital_gain,capital_loss,hours_per_week,native_country,income,...,hours_Heavy,marital_Married,marital_Separated,marital_Single,rel_Husband,rel_Not-in-family,rel_Other-relative,rel_Own-child,rel_Unmarried,rel_Wife
0,39,State-gov,13,Adm-clerical,1,2174,0,40,United-States,0,...,False,False,False,True,False,True,False,False,False,False
1,50,Self-emp-not-inc,13,Exec-managerial,1,0,0,13,United-States,0,...,False,True,False,False,True,False,False,False,False,False
2,38,Private,9,Handlers-cleaners,1,0,0,40,United-States,0,...,False,False,True,False,False,True,False,False,False,False
3,53,Private,7,Handlers-cleaners,1,0,0,40,United-States,0,...,False,True,False,False,True,False,False,False,False,False
4,28,Private,13,Prof-specialty,0,0,0,40,Cuba,0,...,False,True,False,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,39,Private,13,Prof-specialty,0,0,0,36,United-States,0,...,False,False,True,False,False,True,False,False,False,False
48838,64,Unknown,9,Unknown,1,0,0,40,United-States,0,...,False,False,False,True,False,False,True,False,False,False
48839,38,Private,13,Prof-specialty,1,0,0,50,United-States,0,...,False,True,False,False,True,False,False,False,False,False
48840,44,Private,13,Adm-clerical,1,5455,0,40,United-States,0,...,False,False,True,False,False,False,False,True,False,False
48841,35,Self-emp-inc,13,Exec-managerial,1,0,0,60,United-States,1,...,False,True,False,False,True,False,False,False,False,False

# Workclass Column

In [142]:
def group_workclass(x):
    if x == 'Private':
        return 'Private'
    elif x in ['Self-emp-not-inc', 'Self-emp-inc']:
        return 'Self-employed'
    elif x in ['Local-gov', 'State-gov', 'Federal-gov']:
        return 'Government'
    else:
        return 'Other'

df['workclass_grouped'] = df['workclass'].apply(group_workclass)
df

,age,workclass,education_num,occupation,sex,capital_gain,capital_loss,hours_per_week,native_country,income,...,marital_Married,marital_Separated,marital_Single,rel_Husband,rel_Not-in-family,rel_Other-relative,rel_Own-child,rel_Unmarried,rel_Wife,workclass_grouped
0,39,State-gov,13,Adm-clerical,1,2174,0,40,United-States,0,...,False,False,True,False,True,False,False,False,False,Government
1,50,Self-emp-not-inc,13,Exec-managerial,1,0,0,13,United-States,0,...,True,False,False,True,False,False,False,False,False,Self-employed
2,38,Private,9,Handlers-cleaners,1,0,0,40,United-States,0,...,False,True,False,False,True,False,False,False,False,Private
3,53,Private,7,Handlers-cleaners,1,0,0,40,United-States,0,...,True,False,False,True,False,False,False,False,False,Private
4,28,Private,13,Prof-specialty,0,0,0,40,Cuba,0,...,True,False,False,False,False,False,False,False,True,Private
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,39,Private,13,Prof-specialty,0,0,0,36,United-States,0,...,False,True,False,False,True,False,False,False,False,Private
48838,64,Unknown,9,Unknown,1,0,0,40,United-States,0,...,False,False,True,False,False,True,False,False,False,Other
48839,38,Private,13,Prof-specialty,1,0,0,50,United-States,0,...,True,False,False,True,False,False,False,False,False,Private
48840,44,Private,13,Adm-clerical,1,5455,0,40,United-States,0,...,False,True,False,False,False,False,True,False,False,Private
48841,35,Self-emp-inc,13,Exec-managerial,1,0,0,60,United-States,1,...,True,False,False,True,False,False,False,False,False,Self-employed

In [31]:
df['workclass_grouped'].value_counts()

workclass_grouped
Private          33906
Government        6549
Self-employed     5557
Other             2830
Name: count, dtype: int64

In [143]:
workclass_dummies = pd.get_dummies(df['workclass_grouped'], prefix='workclass')
df = pd.concat([df,workclass_dummies], axis=1)
df = df.drop('workclass', axis=1)
df = df.drop('workclass_grouped', axis=1)
df

,age,education_num,occupation,sex,capital_gain,capital_loss,hours_per_week,native_country,income,capital_net,...,rel_Husband,rel_Not-in-family,rel_Other-relative,rel_Own-child,rel_Unmarried,rel_Wife,workclass_Government,workclass_Other,workclass_Private,workclass_Self-employed
0,39,13,Adm-clerical,1,2174,0,40,United-States,0,2174,...,False,True,False,False,False,False,True,False,False,False
1,50,13,Exec-managerial,1,0,0,13,United-States,0,0,...,True,False,False,False,False,False,False,False,False,True
2,38,9,Handlers-cleaners,1,0,0,40,United-States,0,0,...,False,True,False,False,False,False,False,False,True,False
3,53,7,Handlers-cleaners,1,0,0,40,United-States,0,0,...,True,False,False,False,False,False,False,False,True,False
4,28,13,Prof-specialty,0,0,0,40,Cuba,0,0,...,False,False,False,False,False,True,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,39,13,Prof-specialty,0,0,0,36,United-States,0,0,...,False,True,False,False,False,False,False,False,True,False
48838,64,9,Unknown,1,0,0,40,United-States,0,0,...,False,False,True,False,False,False,False,True,False,False
48839,38,13,Prof-specialty,1,0,0,50,United-States,0,0,...,True,False,False,False,False,False,False,False,True,False
48840,44,13,Adm-clerical,1,5455,0,40,United-States,0,5455,...,False,False,False,True,False,False,False,False,True,False
48841,35,13,Exec-managerial,1,0,0,60,United-States,1,0,...,True,False,False,False,False,False,False,False,False,True

# Occupation Column

In [144]:
def group_occupation(x):
    if x in ['Exec-managerial', 'Prof-specialty']:
        return 'White-collar'
    elif x in ['Craft-repair', 'Machine-op-inspct']:
        return 'Blue-collar'
    elif x in ['Sales', 'Adm-clerical']:
        return 'Service'
    else:
        return 'Other'

df['occupation_group'] = df['occupation'].apply(group_occupation)

In [145]:
# Onehot encoding Occupation columns:
occupation_dummies = pd.get_dummies(df['occupation_group'], prefix='occupation')
df = pd.concat([df,occupation_dummies], axis=1)

# Dropping the original workclass column:
df = df.drop('occupation', axis=1)
df = df.drop('occupation_group', axis=1)
df

,age,education_num,sex,capital_gain,capital_loss,hours_per_week,native_country,income,capital_net,race_Amer-Indian-Eskimo,...,rel_Unmarried,rel_Wife,workclass_Government,workclass_Other,workclass_Private,workclass_Self-employed,occupation_Blue-collar,occupation_Other,occupation_Service,occupation_White-collar
0,39,13,1,2174,0,40,United-States,0,2174,False,...,False,False,True,False,False,False,False,False,True,False
1,50,13,1,0,0,13,United-States,0,0,False,...,False,False,False,False,False,True,False,False,False,True
2,38,9,1,0,0,40,United-States,0,0,False,...,False,False,False,False,True,False,False,True,False,False
3,53,7,1,0,0,40,United-States,0,0,False,...,False,False,False,False,True,False,False,True,False,False
4,28,13,0,0,0,40,Cuba,0,0,False,...,False,True,False,False,True,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,39,13,0,0,0,36,United-States,0,0,False,...,False,False,False,False,True,False,False,False,False,True
48838,64,9,1,0,0,40,United-States,0,0,False,...,False,False,False,True,False,False,False,True,False,False
48839,38,13,1,0,0,50,United-States,0,0,False,...,False,False,False,False,True,False,False,False,False,True
48840,44,13,1,5455,0,40,United-States,0,5455,False,...,False,False,False,False,True,False,False,False,True,False
48841,35,13,1,0,0,60,United-States,1,0,False,...,False,False,False,False,False,True,False,False,False,True

 # Native_Country

In [146]:
df['native_country'] = df['native_country'].apply(
    lambda x: 'US' if x == 'United-States' else 'Non-US'
)

In [147]:
# Binary transofrmation on native_country column

df['native_country'] = df['native_country'].map({'US': 1,'Non-US': 0})
df

,age,education_num,sex,capital_gain,capital_loss,hours_per_week,native_country,income,capital_net,race_Amer-Indian-Eskimo,...,rel_Unmarried,rel_Wife,workclass_Government,workclass_Other,workclass_Private,workclass_Self-employed,occupation_Blue-collar,occupation_Other,occupation_Service,occupation_White-collar
0,39,13,1,2174,0,40,1,0,2174,False,...,False,False,True,False,False,False,False,False,True,False
1,50,13,1,0,0,13,1,0,0,False,...,False,False,False,False,False,True,False,False,False,True
2,38,9,1,0,0,40,1,0,0,False,...,False,False,False,False,True,False,False,True,False,False
3,53,7,1,0,0,40,1,0,0,False,...,False,False,False,False,True,False,False,True,False,False
4,28,13,0,0,0,40,0,0,0,False,...,False,True,False,False,True,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,39,13,0,0,0,36,1,0,0,False,...,False,False,False,False,True,False,False,False,False,True
48838,64,9,1,0,0,40,1,0,0,False,...,False,False,False,True,False,False,False,True,False,False
48839,38,13,1,0,0,50,1,0,0,False,...,False,False,False,False,True,False,False,False,False,True
48840,44,13,1,5455,0,40,1,0,5455,False,...,False,False,False,False,True,False,False,False,True,False
48841,35,13,1,0,0,60,1,1,0,False,...,False,False,False,False,False,True,False,False,False,True

In [151]:
# Dropping native_country column, as to avoid bias:
df.drop(['native_country'], axis=1, inplace=True)
df

,age,education_num,sex,hours_per_week,income,capital_net,race_Amer-Indian-Eskimo,race_Asian-Pac-Islander,race_Black,race_Other,...,workclass_Other,workclass_Private,workclass_Self-employed,occupation_Blue-collar,occupation_Other,occupation_Service,occupation_White-collar,has_capital_activity,capital_gain_log,capital_loss_log
0,39,13,1,40,0,2174,False,False,False,False,...,False,False,False,False,False,True,False,1,7.684784,0.0
1,50,13,1,13,0,0,False,False,False,False,...,False,False,True,False,False,False,True,0,0.000000,0.0
2,38,9,1,40,0,0,False,False,False,False,...,False,True,False,False,True,False,False,0,0.000000,0.0
3,53,7,1,40,0,0,False,False,True,False,...,False,True,False,False,True,False,False,0,0.000000,0.0
4,28,13,0,40,0,0,False,False,True,False,...,False,True,False,False,False,False,True,0,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,39,13,0,36,0,0,False,False,False,False,...,False,True,False,False,False,False,True,0,0.000000,0.0
48838,64,9,1,40,0,0,False,False,True,False,...,True,False,False,False,True,False,False,0,0.000000,0.0
48839,38,13,1,50,0,0,False,False,False,False,...,False,True,False,False,False,False,True,0,0.000000,0.0
48840,44,13,1,40,0,5455,False,True,False,False,...,False,True,False,False,False,True,False,1,8.604471,0.0
48841,35,13,1,60,1,0,False,False,False,False,...,False,False,True,False,False,False,True,0,0.000000,0.0

## Creating a new column 'Capital_Net' from capital_gain and capital_loss
### Captures hidden financial behavior
### Improves prediction for high-income group

In [148]:
df['capital_net'] = df['capital_gain'] - df['capital_loss']

df['has_capital_activity'] = (
    (df['capital_gain'] > 0) | (df['capital_loss'] > 0)
).astype(int)

df['capital_gain_log'] = np.log1p(df['capital_gain'])
df['capital_loss_log'] = np.log1p(df['capital_loss'])

In [149]:
# Dropping  redundant columns: Capital_gain & Capital_loss
df.drop(['capital_gain','capital_loss'], axis=1, inplace=True)

### Created 'has_capital_activity' column 
    Converts sparse data → strong signal
    Instead of: Mostly zeros (useless)
    We get:
        0 = no activity
        1 = activity
    Much easier for model to learn
### Log transformation
    1. Reduces skewness: Makes distribution more balanced
    2. Prevents dominance of outliers: Large values don’t overpower model
    3. Helps linear models: 
        Logistic Regression assumes linear relationships
        Log makes relationships smoother

In [150]:
df

,age,education_num,sex,hours_per_week,native_country,income,capital_net,race_Amer-Indian-Eskimo,race_Asian-Pac-Islander,race_Black,...,workclass_Other,workclass_Private,workclass_Self-employed,occupation_Blue-collar,occupation_Other,occupation_Service,occupation_White-collar,has_capital_activity,capital_gain_log,capital_loss_log
0,39,13,1,40,1,0,2174,False,False,False,...,False,False,False,False,False,True,False,1,7.684784,0.0
1,50,13,1,13,1,0,0,False,False,False,...,False,False,True,False,False,False,True,0,0.000000,0.0
2,38,9,1,40,1,0,0,False,False,False,...,False,True,False,False,True,False,False,0,0.000000,0.0
3,53,7,1,40,1,0,0,False,False,True,...,False,True,False,False,True,False,False,0,0.000000,0.0
4,28,13,0,40,0,0,0,False,False,True,...,False,True,False,False,False,False,True,0,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,39,13,0,36,1,0,0,False,False,False,...,False,True,False,False,False,False,True,0,0.000000,0.0
48838,64,9,1,40,1,0,0,False,False,True,...,True,False,False,False,True,False,False,0,0.000000,0.0
48839,38,13,1,50,1,0,0,False,False,False,...,False,True,False,False,False,False,True,0,0.000000,0.0
48840,44,13,1,40,1,0,5455,False,True,False,...,False,True,False,False,False,True,False,1,8.604471,0.0
48841,35,13,1,60,1,1,0,False,False,False,...,False,False,True,False,False,False,True,0,0.000000,0.0

In [152]:
# Converting  boolean to int
pd.set_option('future.no_silent_downcasting', True)
df = df.replace({True: 1, False: 0})

In [153]:
# Dropping target 'Income' column, before testing with the model
df = df.drop('income', axis=1)
df

,age,education_num,sex,hours_per_week,capital_net,race_Amer-Indian-Eskimo,race_Asian-Pac-Islander,race_Black,race_Other,race_White,...,workclass_Other,workclass_Private,workclass_Self-employed,occupation_Blue-collar,occupation_Other,occupation_Service,occupation_White-collar,has_capital_activity,capital_gain_log,capital_loss_log
0,39,13,1,40,2174,0,0,0,0,1,...,0,0,0,0,0,1,0,1,7.684784,0.0
1,50,13,1,13,0,0,0,0,0,1,...,0,0,1,0,0,0,1,0,0.000000,0.0
2,38,9,1,40,0,0,0,0,0,1,...,0,1,0,0,1,0,0,0,0.000000,0.0
3,53,7,1,40,0,0,0,1,0,0,...,0,1,0,0,1,0,0,0,0.000000,0.0
4,28,13,0,40,0,0,0,1,0,0,...,0,1,0,0,0,0,1,0,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,39,13,0,36,0,0,0,0,0,1,...,0,1,0,0,0,0,1,0,0.000000,0.0
48838,64,9,1,40,0,0,0,1,0,0,...,1,0,0,0,1,0,0,0,0.000000,0.0
48839,38,13,1,50,0,0,0,0,0,1,...,0,1,0,0,0,0,1,0,0.000000,0.0
48840,44,13,1,40,5455,0,1,0,0,0,...,0,1,0,0,0,1,0,1,8.604471,0.0
48841,35,13,1,60,0,0,0,0,0,1,...,0,0,1,0,0,0,1,0,0.000000,0.0

In [154]:
# Co-relation to detect redundant columns 
df.corr()

,age,education_num,sex,hours_per_week,capital_net,race_Amer-Indian-Eskimo,race_Asian-Pac-Islander,race_Black,race_Other,race_White,...,workclass_Other,workclass_Private,workclass_Self-employed,occupation_Blue-collar,occupation_Other,occupation_Service,occupation_White-collar,has_capital_activity,capital_gain_log,capital_loss_log
age,1.000000,0.030940,0.088120,0.071558,0.073916,-0.014019,-0.010260,-0.017324,-0.033295,0.032023,...,0.026754,-0.191263,0.178528,-0.001955,-0.057021,-0.053201,0.115251,0.130302,0.123892,0.051706
education_num,0.030940,1.000000,0.009328,0.143689,0.120387,-0.026488,0.064153,-0.074364,-0.044093,0.049287,...,-0.080579,-0.118599,0.060443,-0.218602,-0.281323,0.030088,0.473622,0.143262,0.129068,0.078352
sex,0.088120,0.009328,1.000000,0.228560,0.044494,-0.013003,-0.003363,-0.111481,-0.009774,0.101034,...,-0.063628,-0.033845,0.137274,0.212048,0.005194,-0.210702,0.007398,0.078048,0.067523,0.042801
hours_per_week,0.071558,0.143689,0.228560,1.000000,0.078962,-0.001194,-0.007773,-0.047961,-0.009017,0.046606,...,-0.172210,-0.018147,0.151701,0.052397,-0.133525,-0.052930,0.149358,0.093715,0.084471,0.051705
capital_net,0.073916,0.120387,0.044494,0.078962,1.000000,-0.006466,0.010788,-0.020259,-0.000873,0.013645,...,-0.018554,-0.035513,0.080793,-0.030869,-0.059844,-0.014776,0.107169,0.344151,0.565583,-0.085105
race_Amer-Indian-Eskimo,-0.014019,-0.026488,-0.013003,-0.001194,-0.006466,1.000000,-0.017660,-0.032108,-0.009025,-0.239401,...,0.006972,-0.021973,-0.011541,0.000594,0.016808,-0.008483,-0.010621,-0.011742,-0.005705,-0.011927
race_Asian-Pac-Islander,-0.010260,0.064153,-0.003363,-0.007773,0.010788,-0.017660,1.000000,-0.058358,-0.016403,-0.435128,...,0.004537,-0.002940,-0.003278,-0.024523,-0.009756,0.005435,0.027414,0.002650,0.001549,0.003383
race_Black,-0.017324,-0.074364,-0.111481,-0.047961,-0.020259,-0.032108,-0.058358,1.000000,-0.029822,-0.791096,...,0.017421,-0.000500,-0.078612,-0.013578,0.074437,0.004118,-0.072770,-0.035209,-0.029685,-0.019748
race_Other,-0.033295,-0.044093,-0.009774,-0.009017,-0.000873,-0.009025,-0.016403,-0.029822,1.000000,-0.222358,...,0.007215,0.014759,-0.017181,0.016814,0.009184,-0.006128,-0.019189,-0.010423,-0.009486,-0.004476
race_White,0.032023,0.049287,0.101034,0.046606,0.013645,-0.239401,-0.435128,-0.791096,-0.222358,1.000000,...,-0.020603,0.004155,0.075003,0.018948,-0.064483,-0.002192,0.055247,0.034088,0.028095,0.019312
hours_Part-time,-0.054773,-0.090250,-0.161825,-0.688617,-0.035109,-0.005722,0.003292,-0.005368,-0.004944,0.005729,...,0.173921,-0.051873,-0.014183,-0.122626,0.152913,0.039129,-0.093952,-0.057190,-0.049645,-0.033282
hours_Full-time,-0.028990,-0.103517,-0.080875,-0.165957,-0.051981,0.017455,0.021125,0.097486,0.022634,-0.102637,...,-0.026467,0.071873,-0.156037,0.105589,0.000752,0.007108,-0.102651,-0.058946,-0.055092,-0.028704
hours_Overtime,0.060472,0.173236,0.182680,0.482305,0.066558,-0.016256,-0.026966,-0.092606,-0.019737,0.100355,...,-0.091251,-0.010709,0.127637,-0.012164,-0.127645,-0.025475,0.174471,0.095831,0.087496,0.048935
hours_Heavy,0.030988,0.024723,0.068958,0.521679,0.043324,0.002157,0.001863,-0.031229,-0.004871,0.025861,...,-0.020272,-0.075790,0.140376,-0.036758,0.031341,-0.028009,0.026037,0.031249,0.027371,0.019486
marital_Married,0.315143,0.080747,0.429960,0.213975,0.077570,-0.020078,0.009670,-0.123363,-0.013274,0.107411,...,-0.062048,-0.094894,0.164409,0.115906,-0.100928,-0.108212,0.110229,0.146905,0.131024,0.072495
marital_Separated,0.126511,-0.029935,-0.259467,0.015248,-0.018168,0.015992,-0.037895,0.060003,-0.002934,-0.035183,...,-0.024893,0.018374,-0.041606,-0.018377,-0.016875,0.048212,-0.011732,-0.039046,-0.032616,-0.022482
marital_Single,-0.422121,-0.060078,-0.242743,-0.232131,-0.065881,0.008347,0.019262,0.080783,0.015934,-0.083493,...,0.083099,0.083564,-0.137243,-0.105202,0.116958,0.074271,-0.104480,-0.121190,-0.109792,-0.057327
rel_Husband,0.315799,0.072659,0.579310,0.248574,0.072720,-0.023393,-0.005811,-0.124728,-0.018794,0.118529,...,-0.075622,-0.085209,0.169373,0.146287,-0.092601,-0.128972,0.093921,0.133685,0.117950,0.067990
rel_Not-in-family,-0.009538,0.057004,-0.168916,0.005109,-0.022415,0.001878,-0.017890,0.002547,0.000208,0.006117,...,-0.012441,0.038603,-0.059805,-0.049967,-0.010750,0.023503,0.033907,-0.038565,-0.036392,-0.015584
rel_Other-relative,-0.067945,-0.085253,-0.047735,-0.047419,-0.019243,0.009109,0.051965,0.039230,0.037153,-0.070545,...,0.009500,0.038954,-0.035936,-0.004143,0.051293,0.009683,-0.061453,-0.034864,-0.030667,-0.017490
rel_Own-child,-0.432990,-0.097316,-0.103624,-0.251827,-0.049224,-0.003447,0.004309,0.021469,-0.003747,-0.018161,...,0.107390,0.051576,-0.093577,-0.062314,0.124345,0.064299,-0.141444,-0.097472,-0.087018,-0.047270
rel_Unmarried,0.041670,-0.059461,-0.316325,-0.034536,-0.026901,0.029894,-0.011311,0.148007,0.010595,-0.129247,...,-0.010567,0.017724,-0.053671,-0.040681,0.008491,0.061619,-0.032240,-0.050537,-0.041603,-0.031842
rel_Wife,0.023430,0.035749,-0.317284,-0.066714,0.016506,0.005479,0.016877,0.000785,0.003833,-0.011486,...,0.024638,-0.027759,-0.001878,-0.066484,-0.029841,0.042958,0.050722,0.037927,0.035678,0.015742
workclass_Government,0.073908,0.159290,-0.038532,0.001245,-0.014549,0.035686,0.003920,0.061990,-0.008894,-0.061387,...,-0.097591,-0.592890,-0.140995,-0.117846,-0.033913,-0.022122,0.164276,0.016112,0.008785,0.011730
workclass_Other,0.026754,-0.080579,-0.063628,-0.172210,-0.018554,0.006972,0.004537,0.017421,0.007215,-0.020603,...,1.000000,-0.373662,-0.088861,-0.118272,0.348368,-0.133777,-0.143354,-0.022986,-0.021781,-0.012615
workclass_Private,-0.191263,-0.118599,-0.033845,-0.018147,-0.035513,-0.021973,-0.002940,-0.000500,0.014759,0.004155,...,-0.373662,1.000000,-0.539849,0.146923,-0.104992,0.098674,-0.113300,-0.043732,-0.038126,-0.023383
workclass_Self-employed,0.178528,0.060443,0.137274,0.151701,0.080793,-0.011541,-0.003278,-0.078612,-0.017181,0.075003,...,-0.088861,-0.539849,1.000000,0.000294,-0.067583,-0.021009,0.093592,0.063078,0.061920,0.030623
occupation_Blue-collar,-0.001955,-0.218602,0.212048,0.052397,-0.030869,0.000594,-0.024523,-0.013578,0.016814,0.018948,...,-0.118272,0.146923,0.000294,1.000000,-0.339987,-0.260328,-0.277623,-0.022118,-0.020789,-0.013759
occupation_Other,-0.057021,-0.281323,0.005194,-0.133525,-0.059844,0.016808,-0.009756,0.074437,0.009184,-0.064483,...,0.348368,-0.104992,-0.067583,-0.339987,1.000000,-0.384769,-0.410332,-0.084407,-0.075275,-0.044490
occupation_Service,-0.053201,0.030088,-0.210702,-0.052930,-0.014776,-0.008483,0.005435,0.004118,-0.006128,-0.002192,...,-0.133777,0.098674,-0.021009,-0.260328,-0.384769,1.000000,-0.314190,-0.020892,-0.019852,-0.009063
occupation_White-collar,0.115251,0.473622,0.007398,0.149358,0.107169,-0.010621,0.027414,-0.072770,-0.019189,0.055247,...,-0.143354,-0.113300,0.093592,-0.277623,-0.410332,-0.314190,1.000000,0.131941,0.119803,0.069550
has_capital_activity,0.130302,0.143262,0.078048,0.093715,0.344151,-0.011742,0.002650,-0.035209,-0.010423,0.034088,...,-0.022986,-0.043732,0.063078,-0.022118,-0.084407,-0.020892,0.131941,1.000000,0.772971,0.574087
capital_gain_log,0.123892,0.129068,0.067523,0.084471,0.565583,-0.005705,0.001549,-0.029685,-0.009486,0.028095,...,-0.021781,-0.038126,0.061920,-0.020789,-0.075275,-0.019852,0.119803,0.772971,1.000000,-0.065919
capital_loss_log,0.051706,0.078352,0.042801,0.051705,-0.085105,-0.011927,0.003383,-0.019748,-0.004476,0.019312,...,-0.012615,-0.023383,0.030623,-0.013759,-0.044490,-0.009063,0.069550,0.574087,-0.065919,1.000000

In [155]:
# Writing the transformed and engineering data into csv file
df.to_csv('adultdata_engineered.csv', index = False)

# Conclusion:

1. Numerical Features (Kept + Engineered)
Original Numerical:
    age
    education_num
    hours_per_week
    capital_gain
    capital_loss

Engineered Numerical:
    capital_net
    has_capital_activity (0/1)
    capital_gain_log
    capital_loss_log

2. Encoded Categorical Features (One-Hot)
    After applying OneHotEncoder, categorical columns become:
    Workclass (Grouped → Encoded):
    Marital_Status (Grouped)
    Occupation (Grouped)
    Relationship
    Race
    Hours_Per_Week
    Native_Country (Grouped)

4. Binary Features
    sex (0 = Female, 1 = Male)
    has_capital_activity

5. Dropped Features
    fnlwgt
    original categorical columns:
        workclass
        occupation
        marital_status
        race
        relationship
    redundant columns:
        education ( Duplicate with education_num)